config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  resources :quotes

   root 'static_pages#home'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:author, :quote, :background)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<html>
<head>
  <title><%= yield(:title) %> | Myquotes Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar-inverse">
    <div class="container">
      <%= link_to "MyQuotes", '/quotes', id: "logo", class: "navbar-brand"%>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", '/' %></li>
        <li><%= link_to "MyQuotes", '/quotes' %></li>
        <li><%= link_to "New", new_quote_path %></li>
        <li><%= link_to "Help", '/static_pages/help' %></li>
        <li><%= link_to "About", '/static_pages/about' %></li>
      </ul>
    </div>
  </nav>

  <div class="container-fluid">
    
    <%= yield %>
    
  </div>
</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field panel-primary" id="edit">
    <div class="panel-heading"><%= f.label :author %></div><br>
    <%= f.text_field :author %>
  </div>
  <div class="field panel-primary" id="edit">
    <div class="panel-heading"><%= f.label :quote %></div><br>
    <%= f.text_area :quote %>
  </div>
  <div class="field panel-primary" id="edit">
    <div class="panel-heading"><%= f.label :background %></div><br>
    <%= f.text_area :background %>
  </div>
  <div class="field">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote, class: "btn btn-primary btn-small", data: { confirm: 'Are you sure you want to leave without saving?' } %> |
<%= link_to 'Back', quotes_path, class: "btn btn-danger btn-small", data: { confirm: 'Are you sure you want to leave without saving?' } %>

app/views/quotes/index.html.erb
<% provide(:title, "MyQuotes") %>
<p id="notice"><%= notice %></p>


<h1>Listing Quotes</h1>
<div class="panel panel-primary">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Author</th>
      <th>Quote</th>
      <th>Background</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= link_to quote.author, quote, class: "cust-link" %></td>
        <td><%= link_to quote.quote, quote, class: "cust-link" %></td>
        <td><%= link_to quote.background, quote, class: "cust-link" %></td>
        <td><%= link_to 'Show', quote, class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote), class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Quote', new_quote_path, class: "btn btn-small btn-success" %>

app/views/quotes/new.html.erb
<% provide(:title, "New") %>
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path, class: "btn btn-danger btn-small", data: { confirm: 'Are you sure you want to leave without saving?' } %>

app/views/quotes/show.html.erb
<% provide(:title, "View Quote") %>
<p id="notice"><%= notice %></p>
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @quote.author %>
  </div>
  
  <div class="panel-body">
    "<%= @quote.quote %>"
  </div>
  
  <div class="panel-footer">
    <strong>Background:</strong>
    <%= @quote.background %>
  </div>
</div>
<%= link_to 'Edit', edit_quote_path(@quote), class: "btn btn-primary btn-small" %> |
<%= link_to 'Back', quotes_path, class: "btn btn-success btn-small" %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<br/><p id="logo-black">About</p><br/>
<p>This is an app. You're Welcome! :P</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<br/><p id="logo-black">Help Wanted</p><br/>
<p>He who helps himself is he who finds help...</p>~unknown

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<br/>
<p id="logo-black">MyQuotes Application<div id="logo-black" style="font-size: 1.5em;">by Maximilian Michaels</div></p><br/>
<p>Welcome to the Bootstrapped version of my MyQuotes/Static Pages Application.<br/>Please click the logo in the top left or the MyQuotes link on the navbar to be directed to the application...</p>